worldIconData = [
"49 60 256 2",
"   c #000306",
".  c #080d10",
"X  c #0c1215",
"o  c #0f191b",
"O  c #12161a",
"+  c #141a1d",
"@  c #181d21",
"#  c #1a2225",
"$  c #1f292a",
"%  c #252428",
"&  c #242d31",
"*  c #293233",
"=  c #312e2f",
"-  c #343537",
";  c #363b3c",
":  c #393e40",
">  c #3b4143",
",  c #204163",
"<  c #413b3e",
"1  c #484449",
"2  c #484b4d",
"3  c #4c5253",
"4  c #524c51",
"5  c #575a5c",
"6  c #595458",
"7  c #5b6365",
"8  c #615a5e",
"9  c #645c61",
"0  c #6a5e65",
"q  c #686466",
"w  c #6c6c6d",
"e  c #676c75",
"r  c #6e7172",
"t  c #71646c",
"y  c #736a6f",
"u  c #7b6d75",
"i  c #757376",
"p  c #7a7477",
"a  c #7f7f7d",
"s  c #1e5a97",
"d  c #1a5aab",
"f  c #1060bf",
"g  c #205dac",
"h  c #366199",
"j  c #2264b8",
"k  c #2c69b8",
"l  c #0a63cf",
"z  c #0b6bd9",
"x  c #0c70dd",
"c  c #196cd4",
"v  c #1974d9",
"b  c #1c79dc",
"n  c #086de3",
"m  c #0c73e4",
"M  c #0b7bec",
"N  c #1476e6",
"B  c #167ce6",
"V  c #206cca",
"C  c #2776d1",
"Z  c #2379d8",
"A  c #2b7bd6",
"S  c #3677cb",
"D  c #377bd3",
"F  c #227be3",
"G  c #307de1",
"H  c #4f6c98",
"J  c #426fad",
"K  c #5d7cae",
"L  c #607b95",
"P  c #7a7e81",
"I  c #3e86bb",
"U  c #0d81ee",
"Y  c #1484ed",
"T  c #1b84e9",
"R  c #168af2",
"E  c #1b8af0",
"W  c #1791f7",
"Q  c #1c93f4",
"!  c #1d9af6",
"~  c #1ea3f8",
"^  c #2681d9",
"/  c #2a88dc",
"(  c #3783d6",
")  c #328dde",
"_  c #3994db",
"`  c #3b9cdc",
"'  c #2384e6",
"]  c #238beb",
"[  c #2a8be7",
"{  c #2b94ec",
"}  c #2394f2",
"|  c #249bf4",
" . c #2c9bf1",
".. c #328ce9",
"X. c #388ce2",
"o. c #3296e8",
"O. c #329ced",
"+. c #3b94e6",
"@. c #3a9dea",
"#. c #25a1f6",
"$. c #2ca3f4",
"%. c #2dacf7",
"&. c #2fb2f9",
"*. c #3ba4ed",
"=. c #33a4f1",
"-. c #33abf5",
";. c #3bacf2",
":. c #33b2f6",
">. c #3cb3f5",
",. c #3cbafa",
"<. c #5d87ab",
"1. c #6a98b4",
"2. c #4486d0",
"3. c #438bd3",
"4. c #4b8bdb",
"5. c #4495d4",
"6. c #479cd4",
"7. c #598ccd",
"8. c #5991d3",
"9. c #438be4",
"0. c #4794e8",
"q. c #419ee5",
"w. c #4c9be8",
"e. c #5193e1",
"r. c #559de7",
"t. c #589eed",
"y. c #4ba2dc",
"u. c #58a3d0",
"i. c #59aad4",
"p. c #5bb3dd",
"a. c #47a4eb",
"s. c #42abef",
"d. c #4cade8",
"f. c #43b4f4",
"g. c #44baf8",
"h. c #4ab4f1",
"j. c #4bbbf6",
"k. c #57a3ee",
"l. c #52ade3",
"z. c #5ba6ec",
"x. c #54b3e7",
"c. c #54bbee",
"v. c #5cb4e4",
"b. c #5bbcec",
"n. c #628dc5",
"m. c #6799d4",
"M. c #7398ca",
"N. c #66a6c7",
"B. c #68adc5",
"V. c #62b4d7",
"C. c #63b8de",
"Z. c #79a0d3",
"A. c #79aad7",
"S. c #63a3ea",
"D. c #68aef5",
"F. c #64b5ec",
"G. c #63bde7",
"H. c #69b1f7",
"J. c #72aaea",
"K. c #72b3ee",
"L. c #7ab1eb",
"P. c #76baf2",
"I. c #7ab8f2",
"U. c #46c0fd",
"Y. c #53c4f7",
"T. c #5dc4f3",
"R. c #64c4f3",
"E. c #67c9f6",
"W. c #6cc6f2",
"Q. c #72c3e9",
"!. c #7cc3e5",
"~. c #73c9f3",
"^. c #7bcaf1",
"/. c #83757b",
"(. c #81787e",
"). c #8b7c84",
"_. c #83848b",
"`. c #8c8286",
"'. c #898b91",
"]. c #8d9192",
"[. c #928389",
"{. c #958d90",
"}. c #9b8b92",
"|. c #939394",
" X c #9d9396",
".X c #9b9c9d",
"XX c #8a95b0",
"oX c #8f9ab5",
"OX c #908ea0",
"+X c #9192a0",
"@X c #9a9bad",
"#X c #9da1aa",
"$X c #a39497",
"%X c #a59c9d",
"&X c #a99b9f",
"*X c #a59fab",
"=X c #ac9da3",
"-X c #b09da1",
";X c #a7a6ab",
":X c #aba3a8",
">X c #abaaae",
",X c #adb1b3",
"<X c #b3a4a9",
"1X c #b5acb1",
"2X c #b4b4b6",
"3X c #b8b4b7",
"4X c #b9bbbb",
"5X c #84a5d0",
"6X c #8fb1df",
"7X c #83ace0",
"8X c #81b5e5",
"9X c #8ebaec",
"0X c #80bcf2",
"qX c #99bde7",
"wX c #b9bdc8",
"eX c #8bc2f4",
"rX c #9ac4f0",
"tX c #9ecaf2",
"yX c #afc4d9",
"uX c #bcc3d1",
"iX c #a4c4e9",
"pX c #aac5ea",
"aX c #aecaed",
"sX c #a5ccf2",
"dX c #a4d0f5",
"fX c #abd0f7",
"gX c #b8cee6",
"hX c #bcd4f0",
"jX c #bfdbf4",
"kX c #c3b2b7",
"lX c #c3babf",
"zX c #cdbdc7",
"xX c #c4c5c9",
"cX c #cac6c6",
"vX c #cccccd",
"bX c #d3c3cc",
"nX c #d3d3d5",
"mX c #d6d9d8",
"MX c #dbdcdd",
"NX c #c3d7f1",
"BX c #c6d9f1",
"VX c #dee0df",
"CX c #c7e1f3",
"ZX c #dfe1e2",
"AX c #d4e6f9",
"SX c #e0e0df",
"DX c #e4e5e6",
"FX c #ebecec",
"GX c #e4ebf3",
"HX c #edf2f9",
"JX c #f0eff1",
"KX c #f4f5f5",
"LX c #f7f8f8",
"PX c #fefefe",
"IX c Gray100",
"UX c None s None",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXPXUXUXUXUXUXUXUXvXMXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXGXCXsX8XS.k.t.S.L.iXBXHXPXPX{.9 `.nXPXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXPXHXdXP.F.v.d.o.] E E E E ] [ 3.L a 0 }.).u %XKXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXPXAXK.O.| ;.b.W.R.h.=.$.$.$. .| } Q T s , e  X}.u p cXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXHX0XO.! #.-.g.T.~.W.b.>.-.=.=.=.$. .| | ..] A 8.#X X).y 2XPXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXPXjXw.Q ~ $.=.:.,.Y.W.!.G.g.>.f.>.-.=.$. .o.{ | | Q +.5X=X[.0 |.PXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXPXsXO.! | %.&.:.:.>.j.R.^.Q.c.h.j.g.>.;.-.%.O. .#.$.| } { A.;X[.t |.PXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXPXsX .#.$.$.-.:.:.>.s.j.R.^.~.b.c.j.h.f.>.:.=.O.$.$.$.$.$.| { J.1X}.9 .XPXUXUXUXUXUXUX",
"UXUXUXUXUXUXfX .~ %.&.-.:.:.:.,.,.g.T.^.Q.T.j.j.h.f.,.:.*.=.%.$.$.$.$.$.|  .8X1X[.8 2XUXUXUXUXUXUX",
"UXUXUXUXUXAXO.! -.;.:.>.>.>.,.,.,.j.b.R.E.T.j.j.p.h.:.-.*.:.:.-.-.%.-.=.$. .O.qX%Xu 8 DXUXUXUXUXUX",
"UXUXUXUXHXk.Q #.-.-.:.,.g.,.>.>.g.j.g.g.T.R.c.h.g.>.>.*.=.:.:.:.:.&.-.-.%.-. .*.yX}.t `.PXUXUXUXUX",
"UXUXUXUXrX} #.%.&.:.:.,.g.g.g.,.h.f.,.,.j.E.c.>.>.:.;.6.$.:.:.:.:.:.:.:.:.-.$. .K.2X).8 vXUXUXUXUX",
"UXUXUXGX0.{ =.:.f.,.,.g.U.f.h.g.g.>.>.>.>.c.Y.;.-.-.*.=.-.-.:.:.>.>.:.>.:.;.*.$.{ rX$Xy p PXUXUXUX",
"UXUXPXrX{ =.$.:.f.,.x.p.g.j.p.h.g.>.>.;.-.f.Y.>.:.;.6.=.-.:.:.:.>.>.;.>.;.a.;.=. .z.3X/.6 SXUXUXUX",
"UXUXGX0. .$.-.-.:.,.g.g.U.v.p.f.g.f.>.>.-.>.Y.g.-.-.*.-.:.:.-.>.>.>.>.>.>.>.>.-.$. .iX{.0  XPXUXUX",
"UXUXaX4.o.$.-.-.>.g.g.j.j.j.j.f.f.N.s.:.-.-.V.j.-.*.=.&.%.-.-.>.>.>.>.>.>.;.>.>.-. .I.>Xu y KXUXUX",
"UXPXS.9.0.=.%.:.>.f.h.j.j.j.f.d.d.;.;.-.y.-.f.Y.=.O.$.-.-.;.;.>.>.>.>.>.>.f.;.>.;.O.a.uX/.9 nXUXUX",
"UXKX+. .0.w.*.;.>.g.g.h.h.j.f.d.B.;.-.-.y.;.h.Y.;.$.$.-.-.-.;.>.x.f.f.f.f.>.f.;.;. .{ gX[.0 1XUXUX",
"UXAX[  .@.w.w.*.;.,.g.f.h.h.f.f.f.*.;.-.-.;.c.b.1.*.$. .=.-.;.;.i.d.>.f.f.f.f.s.;.O.} tX$Xt '.UXUX",
"PXhXT | $.$.@.w.a.f.g.f.f.f.f.;.;.;.;.-.=.;.j.C.u.` =.*.6.=.;.;.d.i.;.f.g.g.f.s.;.=.Q eX:Xy i PXUX",
"PXsXU } #.$.$.=.w.r.d.f.>.>.;.s.a.=.=.-.$.$.>.G.c.-.$.6.6.=.;.>.h.x.f.f.f.h.f.>.;.=.Q P.1Xy q PXUX",
"PXrXY ! #. .$.-.-.a.r.a.s.;.;.*.*.=.=.=. .| =.v.T.-.=.O. .=.y.u.f.f.f.f.h.f.f.s.;.$.E H.3Xu q PXUX",
"PXqXU ! | $. .=.-.-.*.a.r.w.@.=.O.O.q.` _ } { d.T.f.` O. .=.a.u.f.s.l.f.h.h.f.;.*.$.Q D.3Xu 9 PXUX",
"PXqXm Q | | #.=.*.=.=.=.*.w.e.0.@. .O. .| 5._ ;.b.j.=. . .=.s.>.;.s.u.f.d.h.f.;.*. .Q D.1Xu 9 PXUX",
"PXpXM W Q | | $.=.$.=.=.=.=.@.+.9.3.o.} Q [ [ -.c.b.*. .O.=.;.;.;.;.s.s.d.i.s.*.=. .E L.1Xy q PXUX",
"PXNXM Q Q Q | | {  .$. .=.$. .o. .2.<.3.[ ] } =.x.b.;. . .O.@.*.*.;.s.*.a.y.*.*.$. .Y 9X&Xu w UXUX",
"UXDXv R Q Q | | |  .$.$.$. . .5.` { ( D D D {  .s.c.;.|  ._ O.O.*.;.;.;.*.*.*.5. .{ Y iX Xt _.UXUX",
"UXPX( Y Q Q ! | | #.$.$.$. . ._ o.{ } Q ' ' ( ( 5.l.;.} } { u.@.=.*.@.=.@.O. . ._ ) ..uX`.9 ;XUXUX",
"UXUXm.x R Q ! |  .$.$.$. . .O.O. .{ _ ] ' E E ' G 2.5.) ] } o.o. .O.O.@.@. . .} ] B t.3X).6 vXUXUX",
"UXUXgXv Y R Q | | $.$.=. . .O.O. .{ { ' T E T Y T E @.( D ( X.{ { }  .o.o.} } E T B qX X/.q KXUXUX",
"UXUXKX3.M R Q Q | $.$.$. .O.O.o._ { [ ' E E T T T [ s. .' ' ( ( 2.X.[ { } ] E Y M ..uX[.0 |.UXUXUX",
"UXUXUXaXm T Q Q |  . . . .O.o.o.{ } [ ] ] R E E ] *.x.@.] E E ] [ ..( ( D D A C c 6X<X/.4 VXUXUXUX",
"UXUXUXKX9.M R ] } {  . . . .o.{ { { ' ' / ' 3.' ' s.x.o.' E E ] E Q E ] ' ' F c 9.wX}.t i PXUXUXUX",
"UXUXUXUXhXZ B E E Q } ] {  . . .| ..{ E T ' / ] ] O.d.o.[ [ E E E E E E E R M B iX&X).6 vXUXUXUXUX",
"UXUXUXUXPX7Xz Y E E E T {  .{ { { ( ] T T E T T T { d.a.{ [ ] E E E Y T T M m J.lX[.9 _.PXUXUXUXUX",
"UXUXUXUXUXKX8.z B Y T E ] } { ) ) [ / T T ] ( ^ T { x.l.@.] ] E E R R Y B m t.xX$Xu 4 DXUXUXUXUXUX",
"UXUXUXUXUXUXGX4.z B Y T E E ] [ ( ] ] ' ' I ( ^ ' ) y.l.@.] ] T Y Y Y B m 0.xX&X).1 >XUXUXUXUXUXUX",
"UXUXUXUXUXUXUXGX7.z B B B T E ^ Z ' ] E T T T ^ ' ' ] q.@.' T Y Y B m n 0.wX-X[.1 '.PXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXHXZ.V x B B T Z ' T T T T ^ T T T B o.x.o.' B B B M N e.>X&X[.4 i KXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXPXpXS z N Z C ' T T B B T B v B ' y.a.' F ' B m v M.:X$X`.1 w KXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXGX5Xd j Z C v v B B B B C ( +.+.B N B F A 7.@X=X$Xu 1 _.KXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXcX& , j f l z m m c c b ) ^ c l l C n.oX:X=X}.6 ; .XPXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXPXw + q 1X'.H h g d d d d j k J K XX*X<X<X X0 - w DXPXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXDX> O (.zXbXkX1X*X+X'._._.OX@X<X1XkX=X[.6 = 2 4XLXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXPXMX'.5 < 1 q `.$X<X<X<X<X=X}.`.y 1 - ; w nXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXPXKXxX'.6 : O @ % % % @ @ - 1 i >XDXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXMX# X X X X X - DXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX>Xo # # # # X # 4XUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXxX1 # # # # # @ + 3 FXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXPXKXmX,X].- & # # # @ @ @ # # 2 ].,XMXPXPXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXMX'.2 * @ X X # O X X X X X + + . . + & 3 2XKXPXPXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXMX> + X X . . X X . . . X . . X X . . . . . + q LXPXPXPXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUX.X. X X . . . . . . . . . . . . . . . . . . . . vXKXPXPXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUX|.  . . . . . X X X X X X . . . . . . . . . . + 2XFXPXPXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXMX> . . X O X . . . . . . . X . . X X + + O + 3 xXGXPXPXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXFX#X6 ; * * & $ # + X X X X + # * ; ; : 2 P 2XMXHXPXPXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXPXPXDXxX.XP 7 3 : & @ + # & : 3 5 r _..X2XnXMXFXPXPXPXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXPXPXPXKXFXZXnXvXxXwX4XwXxXxXvXnXnXMXDXGXJXLXPXPXPXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXPXPXPXPXKXKXFXFXDXDXDXDXDXDXDXFXFXFXKXKXPXPXPXPXPXUXUXUXUXUXUXUXUXUXUXUXUX"
]