*Instance, name=rib-1, part=rib
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-2, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 10.2857138769313
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-3, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 20.5714282396451
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-4, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 30.857142289675
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-5, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 41.1428574537282
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-6, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 51.4285710429426
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-7, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 61.7142853522376
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-8, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 71.9999986772997
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-9, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 82.285712089993
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-10, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 92.5714323129852
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-11, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 102.857144742938
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-12, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 113.142856114299
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-13, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 123.428569417382
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-14, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 133.71428461289
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-15, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 143.999999945354
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-16, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 154.285714188271
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-17, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 164.571428355807
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-18, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 174.857142798744
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-19, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 185.142857201256
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-20, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 195.428571644194
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-21, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 205.714285811729
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-22, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 216.000000054646
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-23, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 226.28571538711
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-24, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,           1.,           0.,           0., 236.571430582618
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-25, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,          -1.,           0.,           0., 113.142856114299
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-26, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,          -1.,           0.,           0., 102.857144742938
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-27, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,          -1.,           0.,           0., 92.5714323129852
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-28, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,          -1.,           0.,           0., 82.285712089993
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-29, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,          -1.,           0.,           0., 71.9999986772997
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-30, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,          -1.,           0.,           0., 61.7142853522376
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-31, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,          -1.,           0.,           0., 51.4285710429426
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-32, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,          -1.,           0.,           0., 41.1428574537282
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-33, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,          -1.,           0.,           0., 30.857142289675
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-34, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,          -1.,           0.,           0., 20.5714282396451
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
**  
*Instance, name=rib-35, part=rib
          0.,           0.,           0.
          0.,           0.,           0.,          -1.,           0.,           0., 10.2857138769313
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance