*Instance, instance=rib-1, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-2, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-3, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-4, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-5, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-6, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-7, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-8, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-9, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-10, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-11, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-12, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-13, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-14, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-15, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-16, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-17, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-18, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-19, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-20, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-21, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-22, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-23, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-24, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-25, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-26, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-27, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-28, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-29, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-30, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-31, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-32, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-33, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-34, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance
*Instance, instance=rib-35, library=w_disc_brake_standard
*Import, state=yes, update=no
*Surface, name=top
 rib-top, S1
*Surface, name=bot
 rib-bot, S2
*Surface, name=film
 all,
*End Instance