# -*- coding: mbcs -*-
#
# Abaqus/Viewer Release 2023.HF4 replay file
# Internal Version: 2023_07_21-19.45.57 RELr425 183702
# Run by nguyenb5 on Wed Sep 25 14:43:56 2024
#

# from driverUtils import executeOnCaeGraphicsStartup
# executeOnCaeGraphicsStartup()
#: Executing "onCaeGraphicsStartup()" in the site directory ...
from abaqus import *
from abaqusConstants import *
session.Viewport(name='Viewport: 1', origin=(0.0, 0.0), width=109.73957824707, 
    height=161.056716918945)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].maximize()
from viewerModules import *
from driverUtils import executeOnCaeStartup
executeOnCaeStartup()
o2 = session.openOdb(name='CHD4_with_HE_UEL.odb')
#: Model: C:/LocalUserData/User-data/nguyenb5/CP1000 plastic (final UEL)/CP1000_CHD4_with_HE/CHD4_with_HE_UEL.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     1
#: Number of Meshes:             1
#: Number of Element Sets:       10
#: Number of Node Sets:          8
#: Number of Steps:              2
session.viewports['Viewport: 1'].setValues(displayedObject=o2)
session.viewports['Viewport: 1'].makeCurrent()
leaf = dgo.LeafFromElementSets(elementSets=("CHD4.SOLID", ))
session.viewports['Viewport: 1'].odbDisplay.displayGroup.remove(leaf=leaf)
session.viewports['Viewport: 1'].view.setValues(session.views['Back'])
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.49417, 
    farPlane=0.507631, width=0.042969, height=0.0231984, 
    viewOffsetX=0.00928152, viewOffsetY=-0.000936215)
session.viewports['Viewport: 1'].odbDisplay.commonOptions.setValues(
    visibleEdges=FREE)
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=0 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.494892, 
    farPlane=0.506909, width=0.0381785, height=0.020612, 
    viewOffsetX=0.00305144, viewOffsetY=-0.00287697)
session.viewports['Viewport: 1'].animationController.setValues(
    animationType=TIME_HISTORY)
session.viewports['Viewport: 1'].animationController.play(duration=UNLIMITED)
session.viewports['Viewport: 1'].animationController.setValues(
    animationType=NONE)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR25_EQPLAS', outputPosition=INTEGRATION_POINT, )
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF, timeScale=1, frameRate=6)
session.writeImageAnimation(fileName='eqplas', format=AVI, canvasObjects=(
    session.viewports['Viewport: 1'], ))
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF)
session.writeImageAnimation(fileName='pic_eqplas', format=AVI, canvasObjects=(
    session.viewports['Viewport: 1'], ))
session.viewports['Viewport: 1'].animationController.setValues(
    animationType=TIME_HISTORY)
session.viewports['Viewport: 1'].animationController.play(duration=UNLIMITED)
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF, frameRate=3)
session.writeImageAnimation(fileName='video_eqplas', format=AVI, 
    canvasObjects=(session.viewports['Viewport: 1'], ))
session.viewports['Viewport: 1'].animationController.stop()
session.animationOptions.setValues(timeHistoryMode=TIME_BASED, 
    minTimeAutoCompute=False, minTime=7500, maxTimeAutoCompute=False)
session.animationOptions.setValues(maxTimeAutoCompute=True)
session.viewports['Viewport: 1'].animationController.play(duration=UNLIMITED)
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF, frameRate=2)
session.writeImageAnimation(fileName='video_eqplas', format=AVI, 
    canvasObjects=(session.viewports['Viewport: 1'], ))
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF, frameRate=6)
session.writeImageAnimation(fileName='video_eqplas', format=AVI, 
    canvasObjects=(session.viewports['Viewport: 1'], ))
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF, frameRate=12)
session.writeImageAnimation(fileName='video_eqplas', format=AVI, 
    canvasObjects=(session.viewports['Viewport: 1'], ))
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR27_SIG_H', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR28_SIG_VONMISES', outputPosition=INTEGRATION_POINT, )
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF)
session.writeImageAnimation(fileName='video_sig_von_Mises', format=AVI, 
    canvasObjects=(session.viewports['Viewport: 1'], ))
session.viewports['Viewport: 1'].view.setValues(session.views['Front'])
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.496285, 
    farPlane=0.509803, width=0.0431536, height=0.023298, 
    viewOffsetX=0.000919216, viewOffsetY=-0.00484539)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR25_EQPLAS', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR28_SIG_VONMISES', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].view.setValues(session.views['Back'])
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.49667, 
    farPlane=0.509417, width=0.0405959, height=0.0219171, 
    viewOffsetX=-0.000234356, viewOffsetY=-0.00445793)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR31_PHI', outputPosition=INTEGRATION_POINT, )
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF)
session.writeImageAnimation(fileName='video_phi', format=AVI, canvasObjects=(
    session.viewports['Viewport: 1'], ))
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR33_GC', outputPosition=INTEGRATION_POINT, )
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF)
session.writeImageAnimation(fileName='video_Gc', format=AVI, canvasObjects=(
    session.viewports['Viewport: 1'], ))
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR35_CL_MOL', outputPosition=INTEGRATION_POINT, )
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF)
session.writeImageAnimation(fileName='video_CL_mol', format=AVI, 
    canvasObjects=(session.viewports['Viewport: 1'], ))
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR36_CT_MOL', outputPosition=INTEGRATION_POINT, )
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF)
session.writeImageAnimation(fileName='video_CT_mol', format=AVI, 
    canvasObjects=(session.viewports['Viewport: 1'], ))
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR25_EQPLAS', outputPosition=INTEGRATION_POINT, )
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF)
session.writeImageAnimation(fileName='video_eqplas', format=AVI, 
    canvasObjects=(session.viewports['Viewport: 1'], ))
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR28_SIG_VONMISES', outputPosition=INTEGRATION_POINT, )
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF)
session.writeImageAnimation(fileName='video_von_Mises', format=AVI, 
    canvasObjects=(session.viewports['Viewport: 1'], ))
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR27_SIG_H', outputPosition=INTEGRATION_POINT, )
session.animationOptions.setValues(minTime=7200, maxTimeAutoCompute=False, 
    maxTime=7500)
session.viewports['Viewport: 1'].animationController.setValues(
    animationType=SCALE_FACTOR)
session.viewports['Viewport: 1'].animationController.play(duration=UNLIMITED)
session.viewports['Viewport: 1'].animationController.setValues(
    animationType=HARMONIC)
session.viewports['Viewport: 1'].animationController.play(duration=UNLIMITED)
session.viewports['Viewport: 1'].animationController.setValues(
    animationType=SCALE_FACTOR)
session.viewports['Viewport: 1'].animationController.play(duration=UNLIMITED)
session.viewports['Viewport: 1'].animationController.setValues(
    animationType=NONE)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=0 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=1 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=2 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=3 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=4 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=5 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=6 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=7 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=8 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=9 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=10 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=11 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=12 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=13 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=14 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=15 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=16 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=17 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=18 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=19 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=20 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=21 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=22 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=23 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=24 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=25 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=26 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=27 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=28 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=29 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=30 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=31 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=32 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=33 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=34 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=35 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=36 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=37 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=38 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=39 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=40 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=41 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=42 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=43 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=44 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=45 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=46 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=47 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=48 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=49 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=50 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=51 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=52 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=53 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=54 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=55 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=56 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=57 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=58 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=59 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=60 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=61 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=62 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=63 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=64 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=65 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=66 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=67 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=68 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=69 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=70 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=71 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=72 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=73 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=74 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=75 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=76 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=77 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=78 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=79 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=80 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].animationController.setValues(
    animationType=TIME_HISTORY)
session.viewports['Viewport: 1'].animationController.play(duration=UNLIMITED)
session.viewports['Viewport: 1'].animationController.stop()
session.viewports['Viewport: 1'].animationController.showFirstFrame()
session.viewports['Viewport: 1'].animationController.incrementFrame()
session.viewports['Viewport: 1'].animationController.incrementFrame()
session.viewports['Viewport: 1'].animationController.incrementFrame()
session.viewports['Viewport: 1'].animationController.incrementFrame()
session.viewports['Viewport: 1'].animationController.setValues(
    animationType=NONE)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=0 )
session.viewports[session.currentViewportName].odbDisplay.setFrame(
    step='step2_insitu', frame=54)
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxAutoCompute=OFF, maxValue=5.42624E+08, minAutoCompute=OFF, 
    minValue=-3.39442E+08)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=55 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=56 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=57 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=58 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=59 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=60 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=61 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=62 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=63 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=64 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=65 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=66 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=67 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=68 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=69 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=70 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=71 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=72 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=73 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=74 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=75 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=76 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=77 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=78 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=79 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=80 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=80 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=79 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=78 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=77 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=76 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=75 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=74 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=73 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=72 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=71 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=70 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=69 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=68 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=67 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=66 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=65 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=64 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=63 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=62 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=61 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=0 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=1 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=2 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=3 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=4 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=5 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=6 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=7 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=8 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=9 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=10 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=11 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=12 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=13 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=14 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=15 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=16 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=17 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=18 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=19 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=20 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=21 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=22 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=23 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=24 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=25 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=26 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=27 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=28 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=29 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=30 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=31 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=32 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=33 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=34 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=35 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=36 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=37 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=38 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=39 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=40 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=41 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=80 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=79 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=78 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=77 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=76 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=75 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=74 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=73 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=72 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=71 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=70 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=69 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=68 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=67 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=66 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=65 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=64 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=63 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=62 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=61 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=60 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=59 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=0 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=1 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=0 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=0 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=0 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=0 )
session.animationOptions.setValues(minTime=7500, maxTimeAutoCompute=True)
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF)
session.writeImageAnimation(fileName='video_sig_H', format=AVI, canvasObjects=(
    session.viewports['Viewport: 1'], ))
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=1 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=2 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=3 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=4 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=5 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=6 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=7 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=8 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=9 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=10 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=11 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=12 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=13 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=14 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=15 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=16 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=17 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=18 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=19 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=20 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=21 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=22 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=23 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=24 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=80 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=79 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=78 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=77 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=76 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=75 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=74 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=73 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=72 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=71 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=70 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=69 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=68 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=67 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=66 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=65 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxAutoCompute=ON)
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxAutoCompute=OFF)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=80 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=79 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=78 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=77 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=76 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=77 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=78 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=79 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=80 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxAutoCompute=ON)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=80 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=79 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=78 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=77 )
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxValue=5.5745E+09)
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxAutoCompute=OFF)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=76 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=75 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=74 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=75 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=76 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=77 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=78 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=79 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=80 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports[session.currentViewportName].odbDisplay.setFrame(
    step='step2_insitu', frame=81)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxAutoCompute=ON)
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxAutoCompute=OFF)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=80 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=79 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=78 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=77 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=76 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=75 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=74 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=73 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=72 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=71 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=70 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=69 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=68 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=67 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=66 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=65 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=64 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=63 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=62 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=61 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=60 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=59 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=58 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=57 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=56 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=55 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=54 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=53 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=52 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=51 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=50 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=49 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=48 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=47 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=0 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=1, frame=0 )
session.viewports['Viewport: 1'].animationController.setValues(
    animationType=TIME_HISTORY)
session.viewports['Viewport: 1'].animationController.play(duration=UNLIMITED)
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxValue=4.5745E+09)
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxValue=3.5745E+09)
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    minValue=-4.39442E+08)
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    minValue=-3.39442E+08)
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxValue=2.5745E+09)
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxValue=1.5745E+09)
session.viewports['Viewport: 1'].odbDisplay.contourOptions.setValues(
    maxValue=8.5745E+08)
session.imageAnimationOptions.setValues(vpDecorations=ON, vpBackground=OFF, 
    compass=OFF)
session.writeImageAnimation(fileName='video_sig_H', format=AVI, canvasObjects=(
    session.viewports['Viewport: 1'], ))
