blankData = [
"26 26 1 1",
" 	c None  s None",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
]

createBellowsV63Data = [
"32 32 3 1",
" 	c None  s None",
".	c black",
"r	c red",
"                                ",
"                                ",
"                                ",
"      .    rr                   ",
"      .    rr                   ",
"      .     rrrrrrrrrrrr        ",
"      .      rrrrrrrrrrrr       ",
"                        rr      ",
"                        rr      ",
"      .      rrrrrrrrrrrr       ",
"      .     rrrrrrrrrrrr        ",
"           rr                   ",
"           rr                   ",
"      .     rrrrrrrrrrrr        ",
"      .      rrrrrrrrrrrr       ",
"      .                 rr      ",
"      .                 rr      ",
"             rrrrrrrrrrrr       ",
"            rrrrrrrrrrrr        ",
"      .    rr                   ",
"      .    rr                   ",
"      .     rrrrrrrrrrrr        ",
"      .      rrrrrrrrrrrr       ",
"                        rr      ",
"                        rr      ",
"      .      rrrrrrrrrrrr       ",
"      .     rrrrrrrrrrrr        ",
"      .    rr                   ",
"      .    rr                   ",
"                                ",
"                                ",
"                                ",
]

createBellowsV64Data = [
"26 26 3 1",
" 	c None  s None",
".	c black",
"r	c red",
"   .    rr                ",
"   .    rr                ",
"   .     rrrrrrrrrrrr     ",
"   .      rrrrrrrrrrrr    ",
"                     rr   ",
"                     rr   ",
"   .      rrrrrrrrrrrr    ",
"   .     rrrrrrrrrrrr     ",
"        rr                ",
"        rr                ",
"   .     rrrrrrrrrrrr     ",
"   .      rrrrrrrrrrrr    ",
"   .                 rr   ",
"   .                 rr   ",
"          rrrrrrrrrrrr    ",
"         rrrrrrrrrrrr     ",
"   .    rr                ",
"   .    rr                ",
"   .     rrrrrrrrrrrr     ",
"   .      rrrrrrrrrrrr    ",
"                     rr   ",
"                     rr   ",
"   .      rrrrrrrrrrrr    ",
"   .     rrrrrrrrrrrr     ",
"   .    rr                ",
"   .    rr                ",
]

createBellowsMiniData = [
"17 17 3 1",
" 	c None  s None",
".	c black",
"r	c red",
"     rr          ",
".     rrrrrrrrr  ",
".      rrrrrrrrr ",
".              rr",
".              rr",
"       rrrrrrrrr ",
"      rrrrrrrrr  ",
".    rr          ",
".    rr          ",
".     rrrrrrrrr  ",
".      rrrrrrrrr ",
"               rr",
"               rr",
".      rrrrrrrrr ",
".     rrrrrrrrr  ",
".    rr          ",
".    rr          ",
]

submitV63Data = [
"32 32 2 1",
" 	c None  s None",
"b	c blue",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"         b     b     b          ",
"       bbbbb bbbbb bbbbb        ",
"                                ",
"       bbbbb bbbbb bbbbb        ",
"         b     b     b          ",
"         b     b   bbbbb        ",
"         b     b                ",
"         b     b   bbbbb        ",
"         b     b     b          ",
"       bbbb  bbbbb bbbbb        ",
"                                ",
"       bbbbb bbbbb bbbbb        ",
"         b     b     b          ",
"       bbbbb bbbbb   b          ",
"                     b          ",
"       bbbbb bbbbb   b          ",
"         b     b     b          ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
]

submitV64Data = [
"26 26 2 1",
" 	c None  s None",
"b	c blue",
"                          ",
"                          ",
"                          ",
"                          ",
"                          ",
"      b     b     b       ",
"    bbbbb bbbbb bbbbb     ",
"                          ",
"    bbbbb bbbbb bbbbb     ",
"      b     b     b       ",
"      b     b   bbbbb     ",
"      b     b             ",
"      b     b   bbbbb     ",
"      b     b     b       ",
"    bbbb  bbbbb bbbbb     ",
"                          ",
"    bbbbb bbbbb bbbbb     ",
"      b     b     b       ",
"    bbbbb bbbbb   b       ",
"                  b       ",
"    bbbbb bbbbb   b       ",
"      b     b     b       ",
"                          ",
"                          ",
"                          ",
"                          ",
]

submitMiniData = [
"17 17 2 1",
" 	c None  s None",
"b	c blue",
"  b     b     b  ",
"bbbbb bbbbb bbbbb",
"                 ",
"bbbbb bbbbb bbbbb",
"  b     b     b  ",
"  b     b   bbbbb",
"  b     b        ",
"  b     b   bbbbb",
"  b     b     b  ",
"bbbb  bbbbb bbbbb",
"                 ",
"bbbbb bbbbb bbbbb",
"  b     b     b  ",
"bbbbb bbbbb   b  ",
"              b  ",
"bbbbb bbbbb   b  ",
"  b     b     b  ",
]

stiffnessV63Data = [
"32 32 4 1",
" 	c None  s None",
".	c black",
"w	c grey60",
"y      c red",
"                                ",
"                                ",
"                                ",
"      ...............           ",
"     w.             ..          ",
"     w.             . .         ",
"     w.             .  .        ",
"     w.             .   .       ",
"     w.             .    .      ",
"     w.             .......     ",
"     w.  .                .     ",
"     w. ...               .     ",
"     w.  .                .     ",
"     w.  .                .     ",
"     w.  .               y.     ",
"     w.  .      y       y .     ",
"     w.  .     y y     y  .     ",
"     w.  .    y   y   y   .     ",
"     w.  .   y     y y    .     ",
"     w.  .  y       y     .     ",
"     w.  . y              .     ",
"     w.  .y               .     ",
"     w.  .                .     ",
"     w.  .             .  .     ",
"     w.  ................ .     ",
"     w.                .  .     ",
"     w.                   .     ",
"     w.....................     ",
"     wwwwwwwwwwwwwwwwwwwww      ",
"                                ",
"                                ",
"                                ",
]

stiffnessV64Data = [
"26 26 4 1",
" 	c None  s None",
".	c black",
"w	c grey60",
"y      c red",
"   ...............        ",
"  w.             ..       ",
"  w.             . .      ",
"  w.             .  .     ",
"  w.             .   .    ",
"  w.             .    .   ",
"  w.             .......  ",
"  w.  .                .  ",
"  w. ...               .  ",
"  w.  .                .  ",
"  w.  .                .  ",
"  w.  .               y.  ",
"  w.  .      y       y .  ",
"  w.  .     y y     y  .  ",
"  w.  .    y   y   y   .  ",
"  w.  .   y     y y    .  ",
"  w.  .  y       y     .  ",
"  w.  . y              .  ",
"  w.  .y               .  ",
"  w.  .                .  ",
"  w.  .             .  .  ",
"  w.  ................ .  ",
"  w.                .  .  ",
"  w.                   .  ",
"  w.....................  ",
"  wwwwwwwwwwwwwwwwwwwww   ",
]

stiffnessMiniData = [
"17 17 4 1",
" 	c None  s None",
".	c black",
"w	c grey60",
"y      c red",
" .............   ",
"w.           ..  ",
"w.           . . ",
"w.           ....",
"w.  .           .",
"w. ...          .",
"w.  .         y .",
"w.  .        y  .",
"w.  .   y   y   .",
"w.  .  y y y    .",
"w.  . y   y     .",
"w.  .y          .",
"w.  .        .  .",
"w.  ........... .",
"w.           .  .",
"w................",
"wwwwwwwwwwwwwwww ",
]

